--------------------------------------------------------
--  DROP TABLE AND SEQUENECE
--------------------------------------------------------

DROP TABLE BAT_PRM_LOG;
DROP TABLE BAT_GRP_LOG;
DROP TABLE BAT_PRM;
DROP TABLE BAT_GRP;
DROP TABLE HOST;
DROP TABLE CMMN_CD;
DROP TABLE CMMN_CD_TP;
DROP SEQUENCE SEQ_BAT_GROUP;
DROP SEQUENCE SEQ_BAT_GRP_LOG;
DROP SEQUENCE SEQ_BAT_PRM;
DROP SEQUENCE SEQ_HOST;
--------------------------------------------------------
--  DDL for Table BAT_GRP
--------------------------------------------------------

  CREATE TABLE "BAT_GRP" 
   (	"BAT_GRP_ID" VARCHAR2(150 BYTE), 
	"BAT_GRP_NM" VARCHAR2(150 BYTE), 
	"BAT_GRP_DSC" VARCHAR2(4000 BYTE), 
	"HOST_ID" VARCHAR2(150 BYTE), 
	"AUTO_EXCN_YN" CHAR(1 BYTE) DEFAULT 'N', 
	"CRON" VARCHAR2(300 BYTE), 
	"USE_YN" CHAR(1 BYTE) DEFAULT 'Y', 
	"LAST_MDFR_NM" VARCHAR2(150 BYTE), 
	"LAST_MDFCN_DTTM" DATE, 
	"CRON_DSC" VARCHAR2(4000 BYTE), 
	"FRST_REG_NM" VARCHAR2(150 BYTE), 
	"FRST_REG_DTTM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BAT_GRP_LOG
--------------------------------------------------------

  CREATE TABLE "BAT_GRP_LOG" 
   (	"BAT_GRP_LOG_ID" VARCHAR2(150 BYTE), 
	"BAT_GRP_RTY_CNT" NUMBER(3,0) DEFAULT 0, 
	"BAT_GRP_ID" VARCHAR2(150 BYTE), 
	"BAT_GRP_ST_CD" VARCHAR2(4 BYTE), 
	"BAT_BGNG_DT" DATE, 
	"BAT_END_DT" DATE, 
	"LAST_MDFR_NM" VARCHAR2(150 BYTE), 
	"LAST_MDFCN_DTTM" DATE, 
	"FRST_REG_NM" VARCHAR2(150 BYTE), 
	"FRST_REG_DTTM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BAT_PRM
--------------------------------------------------------

  CREATE TABLE "BAT_PRM" 
   (	"BAT_PRM_ID" VARCHAR2(150 BYTE), 
	"BAT_GRP_ID" VARCHAR2(150 BYTE), 
	"BAT_PRM_NM" VARCHAR2(150 BYTE), 
	"PATH" VARCHAR2(4000 BYTE), 
	"EXCN_ORD" NUMBER(3,0), 
	"PARAM" VARCHAR2(300 BYTE), 
	"PARAM_DSC" VARCHAR2(4000 BYTE), 
	"USE_YN" CHAR(1 BYTE) DEFAULT 'Y', 
	"LAST_MDFR_NM" VARCHAR2(150 BYTE), 
	"LAST_MDFCN_DTTM" DATE, 
	"FRST_REG_NM" VARCHAR2(150 BYTE), 
	"FRST_REG_DTTM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BAT_PRM_LOG
--------------------------------------------------------

  CREATE TABLE "BAT_PRM_LOG" 
   (	"BAT_GRP_LOG_ID" VARCHAR2(150 BYTE), 
	"BAT_GRP_RTY_CNT" NUMBER(3,0), 
	"BAT_PRM_ID" VARCHAR2(150 BYTE), 
	"PARAM" VARCHAR2(300 BYTE), 
	"BAT_PRM_ST_CD" VARCHAR2(4 BYTE) DEFAULT 'BSWT', 
	"RSLT_MSG" VARCHAR2(4000 BYTE), 
	"BAT_BGNG_DT" DATE, 
	"BAT_END_DT" DATE, 
	"EXCN_ORD" NUMBER(3,0), 
	"LAST_MDFR_NM" VARCHAR2(150 BYTE), 
	"LAST_MDFCN_DTTM" DATE, 
	"FRST_REG_NM" VARCHAR2(150 BYTE), 
	"FRST_REG_DTTM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CMMN_CD
--------------------------------------------------------

  CREATE TABLE "CMMN_CD" 
   (	"CD_ID" VARCHAR2(150 BYTE), 
	"CD_NM" VARCHAR2(150 BYTE), 
	"CD_TP_ID" VARCHAR2(150 BYTE), 
	"USE_YN" CHAR(1 BYTE), 
	"LAST_MDFR_NM" VARCHAR2(150 BYTE), 
	"LAST_MDFCN_DTTM" DATE, 
	"FRST_REG_NM" VARCHAR2(150 BYTE), 
	"FRST_REG_DTTM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CMMN_CD_TP
--------------------------------------------------------

  CREATE TABLE "CMMN_CD_TP" 
   (	"CD_TP_ID" VARCHAR2(150 BYTE), 
	"CD_TP_NM" VARCHAR2(150 BYTE), 
	"USE_YN" CHAR(1 BYTE) DEFAULT 'Y', 
	"LAST_MDFR_NM" VARCHAR2(150 BYTE), 
	"LAST_MDFCN_DTTM" DATE, 
	"FRST_REG_NM" VARCHAR2(150 BYTE), 
	"FRST_REG_DTTM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table HOST
--------------------------------------------------------

  CREATE TABLE "HOST" 
   (	"HOST_ID" VARCHAR2(150 BYTE), 
	"HOST_IP" VARCHAR2(20 BYTE), 
	"HOST_PT" NUMBER(5,0), 
	"HOST_NM" VARCHAR2(150 BYTE), 
	"USE_YN" CHAR(1 BYTE) DEFAULT 'Y', 
	"LAST_MDFR_NM" VARCHAR2(150 BYTE), 
	"LAST_MDFCN_DTTM" DATE, 
	"FRST_REG_NM" VARCHAR2(150 BYTE), 
	"FRST_REG_DTTM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BAT_GRP
--------------------------------------------------------

  ALTER TABLE "BAT_GRP" ADD CONSTRAINT "PK_BAT_GRP" PRIMARY KEY ("BAT_GRP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BAT_GRP" MODIFY ("LAST_MDFCN_DTTM" NOT NULL ENABLE);
  ALTER TABLE "BAT_GRP" MODIFY ("LAST_MDFR_NM" NOT NULL ENABLE);
  ALTER TABLE "BAT_GRP" MODIFY ("USE_YN" NOT NULL ENABLE);
  ALTER TABLE "BAT_GRP" MODIFY ("CRON" NOT NULL ENABLE);
  ALTER TABLE "BAT_GRP" MODIFY ("AUTO_EXCN_YN" NOT NULL ENABLE);
  ALTER TABLE "BAT_GRP" MODIFY ("HOST_ID" NOT NULL ENABLE);
  ALTER TABLE "BAT_GRP" MODIFY ("BAT_GRP_NM" NOT NULL ENABLE);
  ALTER TABLE "BAT_GRP" MODIFY ("FRST_REG_DTTM" NOT NULL ENABLE);
  ALTER TABLE "BAT_GRP" MODIFY ("FRST_REG_NM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BAT_GRP_LOG
--------------------------------------------------------

  ALTER TABLE "BAT_GRP_LOG" ADD CONSTRAINT "PK_BAT_GRP_LOG" PRIMARY KEY ("BAT_GRP_LOG_ID", "BAT_GRP_RTY_CNT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BAT_GRP_LOG" MODIFY ("LAST_MDFCN_DTTM" NOT NULL ENABLE);
  ALTER TABLE "BAT_GRP_LOG" MODIFY ("LAST_MDFR_NM" NOT NULL ENABLE);
  ALTER TABLE "BAT_GRP_LOG" MODIFY ("BAT_BGNG_DT" NOT NULL ENABLE);
  ALTER TABLE "BAT_GRP_LOG" MODIFY ("BAT_GRP_ST_CD" NOT NULL ENABLE);
  ALTER TABLE "BAT_GRP_LOG" MODIFY ("BAT_GRP_ID" NOT NULL ENABLE);
  ALTER TABLE "BAT_GRP_LOG" MODIFY ("FRST_REG_DTTM" NOT NULL ENABLE);
  ALTER TABLE "BAT_GRP_LOG" MODIFY ("FRST_REG_NM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BAT_PRM
--------------------------------------------------------

  ALTER TABLE "BAT_PRM" ADD CONSTRAINT "PK_BAT_PRM" PRIMARY KEY ("BAT_PRM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BAT_PRM" MODIFY ("LAST_MDFCN_DTTM" NOT NULL ENABLE);
  ALTER TABLE "BAT_PRM" MODIFY ("LAST_MDFR_NM" NOT NULL ENABLE);
  ALTER TABLE "BAT_PRM" MODIFY ("USE_YN" NOT NULL ENABLE);
  ALTER TABLE "BAT_PRM" MODIFY ("EXCN_ORD" NOT NULL ENABLE);
  ALTER TABLE "BAT_PRM" MODIFY ("PATH" NOT NULL ENABLE);
  ALTER TABLE "BAT_PRM" MODIFY ("BAT_PRM_NM" NOT NULL ENABLE);
  ALTER TABLE "BAT_PRM" MODIFY ("BAT_GRP_ID" NOT NULL ENABLE);
  ALTER TABLE "BAT_PRM" MODIFY ("FRST_REG_DTTM" NOT NULL ENABLE);
  ALTER TABLE "BAT_PRM" MODIFY ("FRST_REG_NM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BAT_PRM_LOG
--------------------------------------------------------

  ALTER TABLE "BAT_PRM_LOG" ADD CONSTRAINT "PK_BAT_PRM_LOG" PRIMARY KEY ("BAT_GRP_LOG_ID", "BAT_GRP_RTY_CNT", "BAT_PRM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BAT_PRM_LOG" MODIFY ("LAST_MDFCN_DTTM" NOT NULL ENABLE);
  ALTER TABLE "BAT_PRM_LOG" MODIFY ("LAST_MDFR_NM" NOT NULL ENABLE);
  ALTER TABLE "BAT_PRM_LOG" MODIFY ("EXCN_ORD" NOT NULL ENABLE);
  ALTER TABLE "BAT_PRM_LOG" MODIFY ("BAT_PRM_ST_CD" NOT NULL ENABLE);
  ALTER TABLE "BAT_PRM_LOG" MODIFY ("FRST_REG_DTTM" NOT NULL ENABLE);
  ALTER TABLE "BAT_PRM_LOG" MODIFY ("FRST_REG_NM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CMMN_CD
--------------------------------------------------------

  ALTER TABLE "CMMN_CD" MODIFY ("FRST_REG_NM" NOT NULL ENABLE);
  ALTER TABLE "CMMN_CD" ADD CONSTRAINT "PK_CMMN_CD" PRIMARY KEY ("CD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CMMN_CD" MODIFY ("LAST_MDFCN_DTTM" NOT NULL ENABLE);
  ALTER TABLE "CMMN_CD" MODIFY ("LAST_MDFR_NM" NOT NULL ENABLE);
  ALTER TABLE "CMMN_CD" MODIFY ("USE_YN" NOT NULL ENABLE);
  ALTER TABLE "CMMN_CD" MODIFY ("CD_TP_ID" NOT NULL ENABLE);
  ALTER TABLE "CMMN_CD" MODIFY ("CD_NM" NOT NULL ENABLE);
  ALTER TABLE "CMMN_CD" MODIFY ("FRST_REG_DTTM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CMMN_CD_TP
--------------------------------------------------------

  ALTER TABLE "CMMN_CD_TP" MODIFY ("FRST_REG_DTTM" NOT NULL ENABLE);
  ALTER TABLE "CMMN_CD_TP" MODIFY ("FRST_REG_NM" NOT NULL ENABLE);
  ALTER TABLE "CMMN_CD_TP" ADD CONSTRAINT "PK_CMMN_CD_TP" PRIMARY KEY ("CD_TP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CMMN_CD_TP" MODIFY ("LAST_MDFCN_DTTM" NOT NULL ENABLE);
  ALTER TABLE "CMMN_CD_TP" MODIFY ("LAST_MDFR_NM" NOT NULL ENABLE);
  ALTER TABLE "CMMN_CD_TP" MODIFY ("USE_YN" NOT NULL ENABLE);
  ALTER TABLE "CMMN_CD_TP" MODIFY ("CD_TP_NM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HOST
--------------------------------------------------------

  ALTER TABLE "HOST" MODIFY ("FRST_REG_DTTM" NOT NULL ENABLE);
  ALTER TABLE "HOST" MODIFY ("FRST_REG_NM" NOT NULL ENABLE);
  ALTER TABLE "HOST" ADD CONSTRAINT "PK_HOST" PRIMARY KEY ("HOST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOST" MODIFY ("LAST_MDFCN_DTTM" NOT NULL ENABLE);
  ALTER TABLE "HOST" MODIFY ("LAST_MDFR_NM" NOT NULL ENABLE);
  ALTER TABLE "HOST" MODIFY ("USE_YN" NOT NULL ENABLE);
  ALTER TABLE "HOST" MODIFY ("HOST_NM" NOT NULL ENABLE);
  ALTER TABLE "HOST" MODIFY ("HOST_PT" NOT NULL ENABLE);
  ALTER TABLE "HOST" MODIFY ("HOST_IP" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BAT_GRP
--------------------------------------------------------

  ALTER TABLE "BAT_GRP" ADD CONSTRAINT "FK_HOST_BAT_GRP" FOREIGN KEY ("HOST_ID")
	  REFERENCES "HOST" ("HOST_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BAT_GRP_LOG
--------------------------------------------------------

  ALTER TABLE "BAT_GRP_LOG" ADD CONSTRAINT "FK_BAT_GRP_BAT_GRP_LOG" FOREIGN KEY ("BAT_GRP_ID")
	  REFERENCES "BAT_GRP" ("BAT_GRP_ID") ENABLE;
  ALTER TABLE "BAT_GRP_LOG" ADD CONSTRAINT "FK_CMMN_CD_BAT_GRP_LOG" FOREIGN KEY ("BAT_GRP_ST_CD")
	  REFERENCES "CMMN_CD" ("CD_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BAT_PRM
--------------------------------------------------------

  ALTER TABLE "BAT_PRM" ADD CONSTRAINT "FK_BAT_GRP_BAT_PRM" FOREIGN KEY ("BAT_GRP_ID")
	  REFERENCES "BAT_GRP" ("BAT_GRP_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BAT_PRM_LOG
--------------------------------------------------------

  ALTER TABLE "BAT_PRM_LOG" ADD CONSTRAINT "FK_BAT_GRP_LOG_BAT_PRM_LOG" FOREIGN KEY ("BAT_GRP_LOG_ID", "BAT_GRP_RTY_CNT")
	  REFERENCES "BAT_GRP_LOG" ("BAT_GRP_LOG_ID", "BAT_GRP_RTY_CNT") ENABLE;
  ALTER TABLE "BAT_PRM_LOG" ADD CONSTRAINT "FK_BAT_PRM_BAT_PRM_LOG" FOREIGN KEY ("BAT_PRM_ID")
	  REFERENCES "BAT_PRM" ("BAT_PRM_ID") ENABLE;
  ALTER TABLE "BAT_PRM_LOG" ADD CONSTRAINT "FK_CMMN_CD_BAT_PRM_LOG" FOREIGN KEY ("BAT_PRM_ST_CD")
	  REFERENCES "CMMN_CD" ("CD_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CMMN_CD
--------------------------------------------------------

  ALTER TABLE "CMMN_CD" ADD CONSTRAINT "FK_CMMN_CD_TP_CMMN_CD" FOREIGN KEY ("CD_TP_ID")
	  REFERENCES "CMMN_CD_TP" ("CD_TP_ID") ENABLE;

--------------------------------------------------------
--  DDL for Sequence SEQ_BAT_GROUP
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_BAT_GROUP"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1;
--------------------------------------------------------
--  DDL for Sequence SEQ_BAT_GRP_LOG
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_BAT_GRP_LOG"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1;
--------------------------------------------------------
--  DDL for Sequence SEQ_BAT_PRM
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_BAT_PRM"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1;
--------------------------------------------------------
--  DDL for Sequence SEQ_HOST
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_HOST"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1;
--------------------------------------------------------
-- sample DML
--------------------------------------------------------	  
Insert into CMMN_CD_TP (CD_TP_ID,CD_TP_NM,USE_YN,LAST_MDFR_NM,LAST_MDFCN_DTTM,FRST_REG_NM,FRST_REG_DTTM) values ('BS','배치상태','Y','admin',sysdate,'admin',sysdate);
Insert into CMMN_CD (CD_ID,CD_NM,CD_TP_ID,USE_YN,LAST_MDFR_NM,LAST_MDFCN_DTTM,FRST_REG_NM,FRST_REG_DTTM) values ('BSFL','실패','BS','Y','admin',sysdate,'admin',sysdate);
Insert into CMMN_CD (CD_ID,CD_NM,CD_TP_ID,USE_YN,LAST_MDFR_NM,LAST_MDFCN_DTTM,FRST_REG_NM,FRST_REG_DTTM) values ('BSWT','대기','BS','Y','admin',sysdate,'admin',sysdate);
Insert into CMMN_CD (CD_ID,CD_NM,CD_TP_ID,USE_YN,LAST_MDFR_NM,LAST_MDFCN_DTTM,FRST_REG_NM,FRST_REG_DTTM) values ('BSRN','실행중','BS','Y','admin',sysdate,'admin',sysdate);
Insert into CMMN_CD (CD_ID,CD_NM,CD_TP_ID,USE_YN,LAST_MDFR_NM,LAST_MDFCN_DTTM,FRST_REG_NM,FRST_REG_DTTM) values ('BSSC','성공','BS','Y','admin',sysdate,'admin',sysdate);
Insert into HOST (HOST_ID,HOST_IP,HOST_PT,HOST_NM,USE_YN,LAST_MDFR_NM,LAST_MDFCN_DTTM,FRST_REG_NM,FRST_REG_DTTM) values ('HOST'||LPAD(SEQ_HOST.NEXTVAL, 8, '0'),'127.0.0.1',50001,'TEST','N','admin',sysdate,'admin',sysdate);
Insert into BAT_GRP (BAT_GRP_ID,BAT_GRP_NM,BAT_GRP_DSC,HOST_ID,AUTO_EXCN_YN,CRON,USE_YN,LAST_MDFR_NM,LAST_MDFCN_DTTM,CRON_DSC,FRST_REG_NM,FRST_REG_DTTM) values ('BGR'||LPAD(SEQ_BAT_GROUP.NEXTVAL, 8, '0'),'TEST','테스트','HOST00000001','N','* /1 * * * ?','N','admin',sysdate,'1분마다','admin',sysdate);
Insert into BAT_PRM (BAT_PRM_ID,BAT_GRP_ID,BAT_PRM_NM,PATH,EXCN_ORD,PARAM,PARAM_DSC,USE_YN,LAST_MDFR_NM,LAST_MDFCN_DTTM,FRST_REG_NM,FRST_REG_DTTM) values ('PRM'||LPAD(SEQ_BAT_PRM.NEXTVAL, 8, '0'),'BGR00000001','실패프로그램','fail-path',1,null,null,'Y','admin',sysdate,'admin',sysdate);